server:
  port: 8080
  address: 0.0.0.0 # listen to all ips, not just localhost

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      
spring:
  cloud:
    config: # Configuration for Spring Cloud Config, config service discovery
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5 # 5 requests per second
                redis-rate-limiter.burstCapacity: 10 # the maximum number of requests a client can make in a very short burst, even if the replenish rate is lower
                key-resolver: "#{@ipKeyResolver}" # refer in code
          routes:
            - id: auth
              uri: lb://auth-service # lb = load balancer
              predicates:
                - Path=/auth/**
            - id: citizen
              uri: lb://citizen-service
              predicates:
                - Path=/citizen/**
              filters:
                - JWTFilter
            - id: complaint
              uri: lb://complaint-service
              predicates:
                - Path=/complaint/**
              filters:
                - JWTFilter
            - id: department-admin
              uri: lb://department-admin-service
              predicates:
                - Path=/department-admin/**
              filters:
                - JWTFilter
            - id: department-staff
              uri: lb://department-staff-service
              predicates:
                - Path=/department-staff/**
              filters:
                - JWTFilter
            - id: issue
              uri: lb://issue-service
              predicates:
                - Path=/issue/**
              filters:
                - JWTFilter
#      discovery:
#        locator:
#          enabled: true # Enable service discovery, so that currently no need for manual routing
#          lower-case-service-id: true

# if discovery locator used --> need to run eureka server
# if static routes used --> no need to run eureka server


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: citizen-service
        url: /citizen/v3/api-docs
      - name: complaint-service
        url: /complaint/v3/api-docs
      - name: department-admin-service
        url: /department-admin/v3/api-docs
      - name: department-staff-service
        url: /department-staff/v3/api-docs
      - name: issue-service
        url: /issue/v3/api-docs



