spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5 # 5 requests per second
                redis-rate-limiter.burstCapacity: 10 # the maximum number of requests a client can make in a very short burst, even if the replenish rate is lower
                key-resolver: "#{@ipKeyResolver}" # refer in code
          routes:
            - id: auth
              uri: lb://AUTHSERVICE # lb = load balancer
              predicates:
                - Path=/auth/**
            - id: citizen
              uri: lb://CITIZENSERVICE
              predicates:
                - Path=/citizen/**
              filters:
                - JWTFilter
            - id: complaint
              uri: lb://COMPLAINTSERVICE
              predicates:
                - Path=/complaint/**
              filters:
                - JWTFilter
            - id: department-admin
              uri: lb://DEPARTMENTADMINSERVICE
              predicates:
                - Path=/department-admin/**
              filters:
                - JWTFilter
            - id: department-staff
              uri: lb://DEPARTMENTSTAFFSERVICE
              predicates:
                - Path=/department-staff/**
              filters:
                - JWTFilter
            - id: issue
              uri: lb://ISSUESERVICE
              predicates:
                - Path=/issue/**
              filters:
                - JWTFilter
#      discovery:
#        locator:
#          enabled: true # Enable service discovery, so that currently no need for manual routing
#          lower-case-service-id: true

# if discovery locator used --> need to run eureka server
# if static routes used --> no need to run eureka server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Although this url is default autoconfigured but still mention it
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs
    urls:
      - name: AUTHSERVICE
        url: /auth/v3/api-docs
      - name: CITIZENSERVICE
        url: /citizen/v3/api-docs
      - name: COMPLAINTSERVICE
        url: /complaint/v3/api-docs
      - name: DEPARTMENTADMINSERVICE
        url: /department-admin/v3/api-docs
      - name: DEPARTMENTSTAFFSERVICE
        url: /department-staff/v3/api-docs
      - name: ISSUESERVICE
        url: /issue/v3/api-docs

management:
  tracing:
    sampling:
      probability: 1.0 # Trace 100% of requests
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

