spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing

      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# distributed tracing using zipkin & sleuth
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
