spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing
eureka:
  client:
    service-url:
      defaultZone: http://192.168.249.47:8761/eureka/
  instance:
    hostname: 192.168.249.47
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
