spring:
  config:
    # Explicitly import the configuration
    import: "configserver:${SPRING_CONFIG_IMPORT:lb://config-server}" # mention of service discovery at api gateway is required
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing

      
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    # REMOVED: hostname: localhost (This is critical)
    # REMOVED: prefer-ip-address: true (Let Docker's DNS handle it)
    
    # This creates a unique ID for each container instance, e.g., "producer:a1b2c3d4"
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# distributed tracing using zipkin & sleuth
management:
  endpoints:
    web:
      exposure:
        # Expose the prometheus endpoint for scraping, and health for probes
        include: prometheus,health
  tracing:
    sampling:
      # Trace 100% of requests. For production, you'd lower this to 0.1 (10%).
      probability: 1.0
  zipkin:
    tracing:
      # Inside Docker, the address of the zipkin container is its service name.
      endpoint: http://zipkin:9411/api/v2/spans


