server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing
    redis: # can use redis docker image for local development
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}

access_token_expiration: 86400000  # 1000*60*60*24 # 1 day
refresh_token_expiration: 604800000  # 1000*60*60*24*7 # 7 days

springdoc:
  api-docs:
    enabled: true
    path: /auth/v3/api-docs
  swagger-ui:
    enabled: true
    path: /auth/docs
