server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: citizen-service
  config:
    import: "configserver:"
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing


springdoc:
  api-docs:
    enabled: true
    path: /citizen/v3/api-docs
  swagger-ui:
    enabled: true
    path: /citizen/docs

