server:
  port: 8083
  address: 0.0.0.0

spring:
  application:
    name: complaint-service

  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing

springdoc:
  api-docs:
    enabled: true
    path: /complaint/v3/api-docs
  swagger-ui:
    enabled: true
    path: /complaint/docs
