server:
  port: 8083
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    app name: complaint-service # This is the name that shows up in Eureka

spring:
  application:
    name: complaint-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_CONNECTION}
      bindings:
        processIssueAcknowledgement-in-0: # <name-of-consumer-method>-in-0
          destination: issue-acknowledgements-topic
          group: complaint-service-ack-group

  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing

springdoc:
  api-docs:
    enabled: true
    path: /complaint/v3/api-docs
  swagger-ui:
    enabled: true
    path: /complaint/docs
