server:
  port: 8084
  address: 0.0.0.0
spring:
  application:
    name: department-admin-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing

springdoc:
  api-docs:
    enabled: true
    path: /department-admin/v3/api-docs
  swagger-ui:
    enabled: true
    path: /department-admin/docs
