server:
  port: 8084
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    app name: department-admin-service # This is the name that shows up in Eureka
    
spring:
  application:
    name: department-admin-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing

springdoc:
  api-docs:
    enabled: true
    path: /department-admin/v3/api-docs
  swagger-ui:
    enabled: true
    path: /department-admin/docs
