server:
  port: 8085
  address: 0.0.0.0

spring:
  application:
    name: department-staff-service
  config:
    import: "configserver:"
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing

springdoc:
  api-docs:
    enabled: true
    path: /department-staff/v3/api-docs
  swagger-ui:
    enabled: true
    path: /department-staff/docs
