server:
  port: 8084
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    app name: department-admin-service # This is the name that shows up in Eureka
    
spring:
  application:
    name: department-admin-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_CONNECTION}
      bindings:
        publish-staff-profile-update-out-0:
          destination: staff-profile-updation-topic
          content-type: application/json
        issue-acknowledged-out-0:
          destination: issue-acknowledgement-topic
          content-type: application/json

springdoc:
  api-docs:
    enabled: true
    path: /department-admin/v3/api-docs
  swagger-ui:
    enabled: true
    path: /department-admin/docs
