server:
  port: 8085
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    app name: department-staff-service # This is the name that shows up in Eureka

spring:
  application:
    name: department-staff-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_CONNECTION}
      bindings:
        processDepartmentStaffProfileUpdateEvent-in-0: # <name-of-consumer-method>-in-0
          destination: staff-profile-updation-topic
          group: staff-profile-updation-group # go into specific, not inter service work
          content-type: application/json

springdoc:
  api-docs:
    enabled: true
    path: /department-staff/v3/api-docs
  swagger-ui:
    enabled: true
    path: /department-staff/docs
