server:
  port: 8086
  address: 0.0.0.0
spring:
  application:
    name: issue-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing

springdoc:
  api-docs:
    enabled: true
    path: /issue/v3/api-docs
  swagger-ui:
    enabled: true
    path: /issue/docs
