server:
  port: 8087
  address: 0.0.0.0
spring:
  application:
    name: scheduler-service
  config:
    import: "configserver:"
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true # indexing
      
